apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend
  description: Frontend application for Pomodoro Cloud-Native project
  annotations:
    github.com/project-slug: NineKama/pomodoro-cloud-native
spec:
  type: website
  owner: team-frontend
  lifecycle: production