apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: datdiep/pomodoro-backend:latest
        name: backend
        ports:
        - containerPort: 80
        resources: {}
        imagePullPolicy: Always
status: {}
