apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pomodoro-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NineKama/pomodoro-cloud-native
    targetRevision: main
    path: argo/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true