apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: frontend:1.4
        name: frontend
        ports:
        - containerPort: 80
        resources: {}
        imagePullPolicy: Never
status: {}
