apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 4000      # Internal cluster port to be used by frontend or other services
    targetPort: 4000  # The port your backend container listens on