apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NineKama/pomodoro-cloud-native
    targetRevision: main
    path: kubernetes/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  hooks:
    - name: trivy-scan-job
      type: PreSync
      manifest: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: trivy-scan-job
        spec:
          backoffLimit: 0
          template:
            spec:
              containers:
              - name: trivy-scan
                image: aquasec/trivy:latest
                command: ["/bin/sh", "-c"]
                args:
                  - |
                    trivy image --severity HIGH,CRITICAL --exit-code 1 datdiep/pomodoro-backend:latest
              restartPolicy: Never