name: Docker Image CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build backend Docker image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/pomodoro-backend:latest ./backend

    - name: Scan backend Docker image with Trivy
      run: |
        docker run --rm aquasec/trivy:latest image --exit-code 1 --severity HIGH,CRITICAL ${{ secrets.DOCKER_HUB_USERNAME }}/pomodoro-backend:latest

    - name: Build and push backend Docker image
      if: success()
      uses: docker/build-push-action@v6
      with:
        context: ./backend
        dockerfile: ./backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pomodoro-backend:latest
  

  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build frontend Docker image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/pomodoro-frontend:latest ./frontend

    - name: Scan frontend Docker image with Trivy
      run: |
        docker run --rm aquasec/trivy:latest image --exit-code 1 --severity HIGH,CRITICAL ${{ secrets.DOCKER_HUB_USERNAME }}/pomodoro-frontend:latest

    - name: Build and push frontend Docker image
      if: success() 
      uses: docker/build-push-action@v6
      with:   
        context: ./frontend
        dockerfile: ./frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pomodoro-frontend:latest